#连接mysql数据库
  spring:
    datasource:
      username: root
      password: 123456
      url: jdbc:mysql://localhost:3306/cmecplatform?useSSL=false&useUnicode=true&amp&characterEncoding=utf-8&serverTimezone=CTT
      driver-class-name: com.mysql.cj.jdbc.Driver
  #整合mybatis
  mybatis:
      config-location: classpath:mybatis/SqlMapConfig.xml
      mapper-locations: classpath:mybatis/mapper/*.xml